### ISSUE TITLE
Can you add Chinese language

### ISSUE THREAD

**Issue by Zhaodaidai** [Reddnek/syncplay-android#30]
This project is so good
Can you add Chinese language, please send me a language template and I will translate it

**Comment by Et0h** [comment]
Good news. Syncplay 1.7.0 supports Simplified Chinese. You can download the beta from https://syncplay.pl/syncplay-1-7-0-beta-1/ thanks to a translation from @lryanner (#500).

Let us know if there are any corrections or improvements needed.

**Comment by Reddnek** [comment]
@Zhaodaidai Glad you liked it.

You can grab [strings.xml](https://github.com/Reddnek/syncplay-android/blob/master/SyncplayApp/src/main/res/values/strings.xml) and edit it using any text editor like [Notepad++](https://notepad-plus-plus.org/downloads/). The format of the translation file is XML, so it's really easy to replace the English texts with Chinese ones, especially with Notepad++'s syntax highlighting which will make it even more simple.

Let's take the very first line for example:
`    <string name="yes">Yes</string>
`
you only have to edit what's between the opening and ending tags. So it should look like this : 
`    <string name="yes">是的</string>
`

That's pretty much it. Should I assign the task to you ?

**Comment by Zhaodaidai** [comment]
Of course, the Chinese language on the PC side is provided by me, I will do it now, this is my honor! And hope that URL playback can be implemented sooner！
![图片](https://user-images.githubusercontent.com/71388480/178824849-592c6724-ea76-4bd1-82e7-6c7c19f0c3a2.png)

**Comment by Reddnek** [comment]
Next version should support URL playback. Good luck with the work.

**Comment by Zhaodaidai** [comment]
Has been completed

Do not allo
[string-chinese.txt](https://github.com/Reddnek/syncplay-android/files/9106104/string-chinese.txt)
w uploading xml, please change txt to xml

**Comment by Reddnek** [comment]
@Zhaodaidai Amazing work. Thank you for the valuable contribution. Credits will be given where credit is due. The translation will be available in the next release sometime this week. Here's a snapshot of how it looks like: 
![image](https://user-images.githubusercontent.com/72363167/178847453-34e126fa-8d97-4e9d-9aa5-ce1552345995.png)

**Comment by Reddnek** [comment]
Feel free to edit [values-zh/strings.xml](https://github.com/Reddnek/syncplay-android/blob/master/SyncplayApp/src/main/res/values-zh/strings.xml) file directly any time you think a text should be modified. There will be a few more texts on every release so I will leave new lines in the file with empty tags. For now, this can be closed.

**Comment by Zhaodaidai** [comment]
Got it. I'll translate when there are new ones
