### ISSUE TITLE
I successfully streamed!

### ISSUE THREAD

**Issue by Zhaodaidai** [Reddnek/syncplay-android#31]
我在MIXplorer里加入了webdav然后在Syncplayer里选择webdav中的文件夹,于是我可以在线播放了!
![图片](https://user-images.githubusercontent.com/71388480/179099720-c865aca1-45e3-487f-8225-0ec3b63f2f5c.png)

**Comment by Reddnek** [comment]
@Zhaodaidai 
It's fasinating how you figured a way around it ! Apparently, Shared playlists are working better than I expected haha.

Would you care explain the details of how you could get this working ? It seems like the files' duration and size are successfuly being loaded too.

**Comment by Zhaodaidai** [comment]
Of course willing,

First, I have Alibaba Cloud Disk,Then I built alist to turn Alibaba cloud disk into webdav

I installed mixplorer on my phone to mount webdav, then set the webdav of Alibaba cloud disk as the homepage and default, and then forcibly stopped the mixplorer and opened it again

So when I select the folder from Syncplay, there is Mixplorer's webdav folder option in the file management

Then I can start enjoying it, but the strange thing is that the mixplorer is only available when adding a folder, but not when selecting a single video file

**Comment by Reddnek** [comment]
@Zhaodaidai, this is interesting. I will try to simulate the same thing when adding URL support to see the kind of "Uri" that Mixplorer returns. This is a very good option to load remote files from remote cloud storages such as Dropbox, Drive...etc

Syncplay Android comes with a built-in video player called ExoPlayer which can play any kind of remote files or URLs. It seems I don't need to configure it in any way to get URLs working. I am still amazed how you manipulated Shared Playlists to play remote files, tricky.

I will also try to add an option that makes it possible for other users to open all avaiable file managers in the system and not only the default one. Some people have issues with their phone's stock (built-in) file manager.

**Comment by Zhaodaidai** [comment]
It is still necessary to add URL playback

Not everyone will configure such a file manager, they will find it more troublesome, or a remote URL is more convenient, of course, webdav is also very easy to use when configured

You need to set the cloud storage you added in the mixplorer as the default and home page, then force stop and restart, and then choose to add a video folder in Syncplay
