### ISSUE TITLE
When trying to load a media file, show all available/possible file managers, and a built-in one

### ISSUE THREAD

**Issue by Reddnek** [Reddnek/syncplay-android#33]
Some users may want to use a different file manager to pick a media file other than the default file manager. The user should be provided a variety of options to load a media file using:
- The default file manager/explorer.
- A custom/3rd-party file manager/explorer.
- An internal/integrated/in-app file manager/explorer.

**Comment by Zhaodaidai** [comment]
come on!

**Comment by Reddnek** [comment]
> come on!

On vacation currently, will release new version as soon as I am home :)

**Comment by Zhaodaidai** [comment]
Great, no wonder it hasn't been updated for a few days

**Comment by Zhaodaidai** [comment]
are you coming back soon

**Comment by Reddnek** [comment]
> are you coming back soon

I am back to working on the next version which I will be releasing within the next few days. I have other projects to take care of, which is why the pace will be slow. Patience is much appreciated.

**Comment by Zhaodaidai** [comment]
OKOK

**Comment by Reddnek** [comment]
@Zhaodaidai Check [v0.9.0](https://github.com/Reddnek/syncplay-android/releases/tag/v0.9.0). It includes the Chinese translation now.
