### ISSUE TITLE
Chat messages not appearing when playback controls are hidden.

### ISSUE THREAD

**Issue by sxryr** [Reddnek/syncplay-android#34]
Chats and other messages are not previewing when playback controls are hidden. However, all messages are visible in message box when playback controls are visible.

**Comment by Reddnek** [comment]
I've noticed the issue and had it mentioned here #18 

It's also already fixed in the next version which I will be releasing soon. For now, you can use 0.7.0 or kindly wait for the next version.

**Comment by Reddnek** [comment]
Fixed as of [v0.9.0](https://github.com/Reddnek/syncplay-android/releases/tag/v0.9.0).
