### ISSUE TITLE
Video constantly fast forwarding when trying to pause & resume

### ISSUE THREAD

**Issue by Ligh7C** [Reddnek/syncplay-android#36]
If I'm hosting a syncplay session on Windows and using the android syncplay client, things work well if the video file is paused on Windows and then plays when the android syncplay client has joined. However, if the syncplay android client pauses & resumes, then the client is never is able to smoothly resume. It constantly stutters and fast forwards. Similarly, if the windows host skips around in the file without pausing and resuming, the android client has the same issue. 

Is there a workaround? I just want to be able to sync up if resuming a file without the constant stutters.

Also, I haven't been able to host a room from android without issues for clients. Does the android app have similar settings to the windows syncplay server? I didn't see the same options for syncing as I did in the windows app.

Thanks for your work on this.

**Comment by Reddnek** [comment]
@Ligh7C I can't say that I fully understood the issue in play here, a screen recording (on phone, or on desktop) would be much appreciated. As far as I understood, there are issues concerning the interoperability between the Android client and the Desktop client especially when it comes to pausing/playing, correct ? I believe I have tested the interoperability in older versions (pre v0.6) but I didn't test it after that, so there could've been some adjustment or feature port that broke things around.

To help debug things and break down the issue, let me know which version you're using for Syncplay PC, and Syncplay Android, also the type of video you're playing (MediaInfo if possible), and as I mentioned before, a screen recording would be much appreciated.

The Android client has been solely focused on porting the essential functionality only such as Chat, syncing position, rewinding when ahead...etc. As you can see in our 'issues' section, many threads are opened that concern porting more features especially those related to fast-forwarding, slowing down, speeding-up ..etc. The app doesn't even have URL support or TLS secured connection yet so I am still way behind the PC version.

I am planning to re-code how the protocol works entirely so it works better (especially considering that there exists so many issues in reconnection, disconnection, etc).

Thank you for your feedback.

**Comment by Reddnek** [comment]
@Ligh7C On second thought, I believe a workaround is possible here. On PC, Syncplay Windows Client, in settings, there is an option that says "fast-forwarding when behind", something of that sort, if it is checked, uncheck it, then try again. If the problem persists, the Android client needs to be optimized.

**Comment by Ligh7C** [comment]
This doesn't seem to fix the issue as I had these settings selected in the syncplay windows client. 
![image](https://user-images.githubusercontent.com/17198470/192155408-8bd78817-2534-4b19-b987-eb9f57d880b9.png)

I'll direct message you a video of the issue so it is more clear. Thanks so much for your help

I'm using Syncplay 1.6.9 on PC and your 0.9.0 android client

**Comment by Reddnek** [comment]
@Ligh7C Do kindly send me the video recording via email : ```evongintoki@gmail.com```

**Comment by Reddnek** [comment]
Closed due to inactivity. If you have any additional feedback, the issue can be reopened.
