### ISSUE TITLE
Add Video by url

### ISSUE THREAD

**Issue by itsboo07** [Reddnek/syncplay-android#37]
Firstly thanks for this project... Kind of buggy but still works great. As a future request can you add option to stream/play video from url instead of local storage

**Comment by Reddnek** [comment]
As mentioned in #22, URL support is already in the works. It should be available by next update, I am working on it. Glad you liked the project.

**Comment by Reddnek** [comment]
Added as of version [0.10.0](https://github.com/Reddnek/syncplay-android/releases/tag/v0.10.0)
