### ISSUE TITLE
video player requests

### ISSUE THREAD

**Issue by itsboo07** [Reddnek/syncplay-android#38]
Need more features to the video player.. Like doubt tap (left/right) to backward/forward. option to edit subtitle size and location(x axis) and plese try to add audio and subtitle delay.... These features could really be helpful

**Comment by Reddnek** [comment]
The video player that is integrated in Syncplay-android is [Google's ExoPlayer](https://github.com/google/ExoPlayer). It doesn't offer much control over subtitles, especially their location. For subtitle size, there already exists an option to edit the subtitle size in the 'Settings' tab outside the room (Main Screen).

As for audio and subtitle delay, that will be taken under consideration, thank you.

**Comment by Reddnek** [comment]
Added double-tap gestures as of the latest version [0.11.0](https://github.com/Reddnek/syncplay-android/releases/tag/v0.11.0). 

Track delays cannot be supported for the meantime as Google's Exoplayer aren't intending to add it as an option any time soon. But it will still be under consideration.
